version: "3"
services:
  node:
    image: node:carbon
    restart: unless-stopped
    user: node
    working_dir: /home/node/app
    depends_on:
      - postgres
    volumes:
      - ..:/home/node/app:cached
    command: "./node_modules/.bin/nodemon -L"
    environment:
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGPORT: 5432
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - node
    volumes:
      - ../static:/var/www:cached
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - "80:80"
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres: