version: "3"
services:
  node:
    image: node:carbon
    restart: unless-stopped
    user: node
    working_dir: /home/node/app
    depends_on:
      - postgres
    volumes:
      - ..:/home/node/app:cached
    ports:
      - "80:3000"
    command: "./node_modules/.bin/nodemon -L"
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres: